### ISSUE TITLE
Can't send a multipart/related message

### ISSUE THREAD

**Issue by gdiet** [dmurvihill/courier#53]
To have programs like Outlook display the HTML part of multipart (HTML & simple text) messages correctly, I have to use the MimeMultipart "multipart/related". I can't find an easy way to do this with courier. I think it could easily be added to the library as follows:

* In case class courier.Multipart add an optional constructor parameter `subtype: String = "mixed"`
* In method courier.Multipart#parts call `new MimeMultipart(subtype)`

With this, I think that my issue could be solved, so I can send an email like this:

    Envelope
      .from(new InternetAddress(from))
      .to(new InternetAddress(to))
      .subject(subject)
      .content(Multipart(subtype = "related").text(textContent).html(htmlContent))

If you want I can provide a pull request.

**Comment by daddykotex** [comment]
Thanks for using coursier.

Do you know if the issue exist with the Outlook web app? (Not the locally
installed app, but the one at outlook.office.com). I ask because I would
like to reproduce, just to make sure we're on the same page, and I only
have access to the web app.

I don't use coursier much myself, so if I could quickly see what happens,
that would be great.

Anyway, you basically did all the work, so I can provide a fix for it
(implement what you've suggested).

**Comment by gdiet** [comment]
After cloning courier to create the patch and pull request I found that the exact code I have proposed was already introduced in 2017 😄, but I didn't see it because I was still on the version `"ch.lightshed" %% "courier" % "0.1.4"`... I Updated to `"com.github.daddykotex" %% "courier" % "2.0.0"`, now I can specify the subtype as required.

Thanks anyway for the quick reply! I'm closing this issue.

**Comment by daddykotex** [comment]
Good news, thanks for the update.
